export type CharacterProfile = {
  name: string;
  source: string;
  aliases: string[];
  qualities: [string, string, string];
};

const profiles: CharacterProfile[] = [
  ["Gojo Satoru", "Jujutsu Kaisen", ["gojo", "satoru", "satoru gojo"], ["confidence", "clarity", "strength"]],
  ["Geto Suguru", "Jujutsu Kaisen", ["geto", "suguru", "suguru geto"], ["composure", "conviction", "understanding"]],
  ["Nanami Kento", "Jujutsu Kaisen", ["nanami", "kento", "kento nanami"], ["steadiness", "practicality", "care"]],
  ["Megumi Fushiguro", "Jujutsu Kaisen", ["megumi", "fushiguro"], ["quiet courage", "loyalty", "discernment"]],
  ["Yuji Itadori", "Jujutsu Kaisen", ["yuji", "itadori", "yuuji"], ["kindness", "resolve", "warmth"]],
  ["Nobara Kugisaki", "Jujutsu Kaisen", ["nobara", "kugisaki"], ["self-respect", "boldness", "honesty"]],
  ["Levi Ackerman", "Attack on Titan", ["levi", "captain levi"], ["discipline", "protection", "precision"]],
  ["Eren Yeager", "Attack on Titan", ["eren", "eren jaeger", "yeager", "jaeger"], ["drive", "freedom", "determination"]],
  ["Mikasa Ackerman", "Attack on Titan", ["mikasa"], ["devotion", "strength", "steadiness"]],
  ["Armin Arlert", "Attack on Titan", ["armin"], ["insight", "hope", "gentleness"]],
  ["Osamu Dazai", "Bungo Stray Dogs", ["dazai", "osamu"], ["wit", "perception", "resilience"]],
  ["Chuuya Nakahara", "Bungo Stray Dogs", ["chuuya", "nakahara", "chūya"], ["fierceness", "loyalty", "grace"]],
  ["Katsuki Bakugo", "My Hero Academia", ["bakugo", "bakugou", "katsuki", "kacchan"], ["ambition", "honesty", "tenacity"]],
  ["Izuku Midoriya", "My Hero Academia", ["deku", "izuku", "midoriya"], ["compassion", "courage", "effort"]],
  ["Shoto Todoroki", "My Hero Academia", ["shoto", "shouto", "todoroki"], ["calm", "growth", "integrity"]],
  ["Keigo Takami", "My Hero Academia", ["hawks", "keigo", "takami"], ["freedom", "perception", "ease"]],
  ["Shota Aizawa", "My Hero Academia", ["aizawa", "eraserhead", "eraser head", "shota"], ["reliability", "patience", "quiet care"]],
  ["L Lawliet", "Death Note", ["l", "lawliet", "ryuzaki", "ryuuzaki"], ["curiosity", "logic", "focus"]],
  ["Light Yagami", "Death Note", ["light", "yagami", "kira"], ["focus", "strategy", "confidence"]],
  ["Kakashi Hatake", "Naruto", ["kakashi", "hatake"], ["wisdom", "adaptability", "loyalty"]],
  ["Itachi Uchiha", "Naruto", ["itachi", "uchiha itachi"], ["sacrifice", "foresight", "calm"]],
  ["Naruto Uzumaki", "Naruto", ["naruto", "uzumaki"], ["hope", "persistence", "belonging"]],
  ["Sasuke Uchiha", "Naruto", ["sasuke", "uchiha sasuke"], ["resolve", "independence", "growth"]],
  ["Killua Zoldyck", "Hunter x Hunter", ["killua", "zoldyck"], ["loyalty", "quickness", "tenderness"]],
  ["Gon Freecss", "Hunter x Hunter", ["gon", "freecss"], ["optimism", "curiosity", "heart"]],
  ["Kurapika", "Hunter x Hunter", ["kurapika"], ["focus", "loyalty", "dignity"]],
  ["Edward Elric", "Fullmetal Alchemist", ["edward", "ed elric", "fullmetal"], ["resolve", "ingenuity", "devotion"]],
  ["Kyo Sohma", "Fruits Basket", ["kyo", "kyou", "sohma"], ["honesty", "growth", "warmth"]],
  ["Tohru Honda", "Fruits Basket", ["tohru", "tooru", "honda"], ["kindness", "acceptance", "hope"]],
  ["Howl Pendragon", "Howl's Moving Castle", ["howl", "pendragon", "howl jenkins"], ["wonder", "sensitivity", "courage"]],
  ["Haku", "Spirited Away", ["kohaku", "nigihayami kohakunushi", "haku"], ["guidance", "calm", "loyalty"]],
  ["Kageyama Tobio", "Haikyu!!", ["kageyama", "tobio", "king of the court"], ["precision", "effort", "growth"]],
  ["Hinata Shoyo", "Haikyu!!", ["shoyo", "shouyou", "hinata shoyo"], ["energy", "hope", "persistence"]],
  ["Giyu Tomioka", "Demon Slayer", ["giyu", "giyuu", "tomioka"], ["calm", "protection", "integrity"]],
  ["Kyojuro Rengoku", "Demon Slayer", ["rengoku", "kyojuro", "kyoujurou"], ["warmth", "courage", "purpose"]],
  ["Tanjiro Kamado", "Demon Slayer", ["tanjiro", "tanjirou", "kamado"], ["compassion", "patience", "resolve"]],
  ["Nezuko Kamado", "Demon Slayer", ["nezuko"], ["gentleness", "protection", "resilience"]],
  ["Sebastian Michaelis", "Black Butler", ["sebastian", "michaelis"], ["competence", "composure", "attention"]],
  ["Jinshi", "The Apothecary Diaries", ["jinshi"], ["grace", "persistence", "perception"]],
  ["Maomao", "The Apothecary Diaries", ["mao mao", "maomao"], ["curiosity", "candor", "intelligence"]],
  ["Frieren", "Frieren: Beyond Journey's End", ["frieren"], ["patience", "memory", "quiet care"]],
  ["Lelouch Lamperouge", "Code Geass", ["lelouch", "zero", "lamperouge"], ["strategy", "resolve", "devotion"]],
  ["Kaworu Nagisa", "Neon Genesis Evangelion", ["kaworu", "nagisa"], ["acceptance", "calm", "understanding"]],
  ["Astarion", "Baldur's Gate 3", ["astarion ancunin", "astarion"], ["wit", "survival", "self-discovery"]],
  ["Gale Dekarios", "Baldur's Gate 3", ["gale", "dekarios"], ["curiosity", "eloquence", "devotion"]],
  ["Shadowheart", "Baldur's Gate 3", ["shart", "jenevelle", "shadowheart"], ["resilience", "faith", "gentleness"]],
  ["Zhongli", "Genshin Impact", ["rex lapis", "morax", "zhongli"], ["wisdom", "steadiness", "perspective"]],
  ["Kaedehara Kazuha", "Genshin Impact", ["kazuha", "kaedehara"], ["freedom", "poise", "reflection"]],
  ["Xiao", "Genshin Impact", ["alatus", "xiao"], ["protection", "endurance", "quiet care"]],
  ["Alhaitham", "Genshin Impact", ["al haitham", "alhaitham"], ["clarity", "independence", "reason"]],
  ["Dan Heng", "Honkai: Star Rail", ["danheng", "dan heng", "imbibitor lunae"], ["calm", "loyalty", "reflection"]],
  ["Jing Yuan", "Honkai: Star Rail", ["jingyuan", "jing yuan", "the general"], ["patience", "strategy", "warmth"]],
  ["Link", "The Legend of Zelda", ["hero of hyrule", "link"], ["courage", "resourcefulness", "quiet devotion"]],
  ["Harry Potter", "Harry Potter", ["harry", "the boy who lived", "potter"], ["courage", "loyalty", "hope"]],
  ["Hermione Granger", "Harry Potter", ["hermione", "granger"], ["intelligence", "loyalty", "conviction"]],
  ["Draco Malfoy", "Harry Potter", ["draco", "malfoy"], ["complexity", "ambition", "growth"]],
  ["Severus Snape", "Harry Potter", ["snape", "severus", "professor snape"], ["devotion", "resolve", "restraint"]],
  ["Sirius Black", "Harry Potter", ["sirius", "padfoot"], ["loyalty", "freedom", "warmth"]],
  ["Remus Lupin", "Harry Potter", ["remus", "lupin", "moony"], ["gentleness", "wisdom", "resilience"]],
  ["Newt Scamander", "Fantastic Beasts", ["newt", "scamander"], ["kindness", "curiosity", "quiet courage"]],
  ["Loki Laufeyson", "Marvel", ["loki", "laufeyson", "god of mischief"], ["wit", "adaptability", "self-discovery"]],
  ["Peter Parker", "Marvel", ["peter", "spider man", "spiderman"], ["responsibility", "kindness", "resilience"]],
  ["Tony Stark", "Marvel", ["tony", "stark", "iron man", "ironman"], ["ingenuity", "confidence", "care"]],
  ["Bucky Barnes", "Marvel", ["bucky", "winter soldier", "james barnes"], ["recovery", "loyalty", "endurance"]],
  ["Steve Rogers", "Marvel", ["steve", "captain america", "cap"], ["integrity", "courage", "steadiness"]],
  ["Wanda Maximoff", "Marvel", ["wanda", "scarlet witch"], ["resilience", "love", "power"]],
  ["Natasha Romanoff", "Marvel", ["natasha", "romanoff", "black widow"], ["resourcefulness", "loyalty", "strength"]],
  ["Thor Odinson", "Marvel", ["thor", "odinson", "god of thunder"], ["courage", "warmth", "renewal"]],
  ["Bruce Wayne", "DC Comics", ["bruce", "wayne", "batman"], ["resolve", "protection", "discipline"]],
  ["Dick Grayson", "DC Comics", ["dick", "grayson", "nightwing", "robin"], ["hope", "leadership", "warmth"]],
  ["Jason Todd", "DC Comics", ["jason", "todd", "red hood"], ["survival", "fierceness", "loyalty"]],
  ["Clark Kent", "DC Comics", ["clark", "kent", "superman", "kal el"], ["hope", "gentleness", "strength"]],
  ["Diana Prince", "DC Comics", ["diana", "wonder woman"], ["truth", "compassion", "courage"]],
  ["Zuko", "Avatar: The Last Airbender", ["prince zuko", "fire lord zuko", "zuko"], ["growth", "honor", "perseverance"]],
  ["Katara", "Avatar: The Last Airbender", ["katara"], ["compassion", "determination", "healing"]],
  ["Azula", "Avatar: The Last Airbender", ["princess azula", "azula"], ["precision", "ambition", "intensity"]],
  ["Aang", "Avatar: The Last Airbender", ["avatar aang", "aang"], ["hope", "balance", "kindness"]],
  ["Sokka", "Avatar: The Last Airbender", ["sokka"], ["wit", "resourcefulness", "loyalty"]],
  ["Percy Jackson", "Percy Jackson", ["percy", "seaweed brain"], ["loyalty", "humor", "courage"]],
  ["Annabeth Chase", "Percy Jackson", ["annabeth", "wise girl"], ["wisdom", "strategy", "devotion"]],
  ["Nico di Angelo", "Percy Jackson", ["nico", "di angelo", "ghost king"], ["resilience", "independence", "loyalty"]],
  ["Will Solace", "Percy Jackson", ["will", "solace"], ["warmth", "healing", "optimism"]],
  ["Wednesday Addams", "The Addams Family", ["wednesday", "wednesday addams"], ["independence", "candor", "composure"]],
  ["Kaz Brekker", "Six of Crows", ["kaz", "brekker", "dirtyhands"], ["strategy", "survival", "resolve"]],
  ["Inej Ghafa", "Six of Crows", ["inej", "ghafa", "the wraith"], ["faith", "courage", "grace"]],
  ["Cardan Greenbriar", "The Folk of the Air", ["cardan", "high king cardan"], ["wit", "vulnerability", "growth"]],
  ["Jude Duarte", "The Folk of the Air", ["jude", "jude duarte"], ["ambition", "courage", "resourcefulness"]],
  ["Peeta Mellark", "The Hunger Games", ["peeta", "mellark"], ["gentleness", "hope", "steadiness"]],
  ["Katniss Everdeen", "The Hunger Games", ["katniss", "everdeen", "mockingjay"], ["protection", "resolve", "love"]],
  ["Frodo Baggins", "The Lord of the Rings", ["frodo", "baggins"], ["endurance", "mercy", "quiet courage"]],
  ["Legolas", "The Lord of the Rings", ["legolas greenleaf", "legolas"], ["grace", "loyalty", "perception"]],
  ["Aragorn", "The Lord of the Rings", ["strider", "elessar", "aragorn"], ["leadership", "humility", "steadiness"]],
  ["Samwise Gamgee", "The Lord of the Rings", ["sam", "samwise", "sam gamgee"], ["loyalty", "hope", "devotion"]],
  ["Xavier", "Love and Deepspace", ["xavier lads", "shen xinghui", "xavier"], ["steadiness", "devotion", "quiet strength"]],
  ["Zayne", "Love and Deepspace", ["zayne lads", "li shen", "zayne"], ["care", "composure", "devotion"]],
  ["Rafayel", "Love and Deepspace", ["rafayel lads", "qi yu", "rafayel"], ["passion", "wit", "tenderness"]],
  ["Sylus", "Love and Deepspace", ["sylus lads", "qin che", "sylus"], ["confidence", "protection", "intensity"]],
  ["Caleb", "Love and Deepspace", ["caleb lads", "xia yizhou", "caleb"], ["warmth", "loyalty", "protectiveness"]],
  ["Victor Li", "Mr Love: Queen's Choice", ["victor", "li zeyan", "victor li"], ["reliability", "ambition", "quiet care"]],
  ["Gavin Bai", "Mr Love: Queen's Choice", ["gavin", "bai qi", "gavin bai"], ["loyalty", "courage", "protection"]],
  ["Lucien Xu", "Mr Love: Queen's Choice", ["lucien", "xu mo", "lucien xu"], ["intelligence", "gentleness", "mystery"]],
  ["Kiro Zhou", "Mr Love: Queen's Choice", ["kiro", "zhou qiluo", "kiro zhou"], ["brightness", "devotion", "hope"]],
  ["Shaw Ling", "Mr Love: Queen's Choice", ["shaw", "ling xiao", "shaw ling"], ["independence", "boldness", "energy"]],
  ["Luke Pearce", "Tears of Themis", ["luke", "xia yan", "luke pearce"], ["loyalty", "warmth", "courage"]],
  ["Artem Wing", "Tears of Themis", ["artem", "zuo ran", "artem wing"], ["steadiness", "integrity", "care"]],
  ["Vyn Richter", "Tears of Themis", ["vyn", "mo yi", "vyn richter"], ["perception", "composure", "gentleness"]],
  ["Marius von Hagen", "Tears of Themis", ["marius", "lu jinghe", "marius von hagen"], ["charisma", "creativity", "devotion"]],
  ["Zen", "Mystic Messenger", ["hyun ryu", "zen mystic messenger", "zen"], ["confidence", "warmth", "devotion"]],
  ["Jumin Han", "Mystic Messenger", ["jumin", "jumin han"], ["reliability", "composure", "loyalty"]],
  ["707", "Mystic Messenger", ["seven", "luciel choi", "saeyoung choi", "707"], ["wit", "resilience", "devotion"]],
  ["Yoosung Kim", "Mystic Messenger", ["yoosung", "yoosung kim"], ["sincerity", "growth", "warmth"]],
  ["V", "Mystic Messenger", ["jihyun kim", "v mystic messenger"], ["gentleness", "reflection", "devotion"]],
  ["Lucifer", "Obey Me!", ["lucifer obey me", "lucifer"], ["leadership", "protection", "devotion"]],
  ["Mammon", "Obey Me!", ["mammon obey me", "mammon"], ["loyalty", "warmth", "spontaneity"]],
  ["Keegan P. Russ", "Call of Duty: Ghosts", ["keegan russ", "keegan p russ", "keegan"], ["reliability", "focus", "protection"]],
  ["Simon Riley", "Call of Duty", ["simon ghost riley", "ghost cod", "ghost", "simon riley"], ["protection", "endurance", "quiet loyalty"]],
  ["König", "Call of Duty", ["konig cod", "koenig", "könig"], ["strength", "focus", "guarded care"]],
  ["John Price", "Call of Duty", ["captain price", "price cod", "john price"], ["leadership", "steadiness", "protection"]],
  ["Leon S. Kennedy", "Resident Evil", ["leon kennedy", "leon s kennedy", "leon"], ["courage", "resilience", "care"]],
  ["Ada Wong", "Resident Evil", ["ada", "ada wong"], ["composure", "independence", "perception"]],
  ["Arthur Morgan", "Red Dead Redemption 2", ["arthur", "arthur morgan"], ["loyalty", "reflection", "redemption"]],
  ["Geralt of Rivia", "The Witcher", ["geralt", "white wolf", "geralt of rivia"], ["steadiness", "protection", "discernment"]],
  ["Garrus Vakarian", "Mass Effect", ["garrus", "vakarian", "archangel"], ["loyalty", "reliability", "wit"]],
  ["Solas", "Dragon Age", ["fen harel", "dread wolf", "solas"], ["wisdom", "reflection", "complexity"]],
  ["Fenris", "Dragon Age", ["fenris dragon age", "fenris"], ["freedom", "resilience", "loyalty"]],
  ["Johnny Silverhand", "Cyberpunk 2077", ["johnny", "silverhand", "johnny silverhand"], ["defiance", "charisma", "conviction"]],
  ["Joel Miller", "The Last of Us", ["joel", "joel miller"], ["protection", "endurance", "devotion"]],
  ["Ais", "Touchstarved", ["ais touchstarved", "ais"], ["confidence", "perception", "protectiveness"]],
  ["Leander", "Touchstarved", ["leander touchstarved", "leander"], ["charisma", "warmth", "confidence"]],
  ["Mhin", "Touchstarved", ["mhin touchstarved", "mhin"], ["independence", "vigilance", "quiet care"]],
  ["Kuras", "Touchstarved", ["kuras touchstarved", "kuras"], ["wisdom", "gentleness", "composure"]],
  ["Vere", "Touchstarved", ["vere touchstarved", "vere"], ["wit", "confidence", "perception"]],
  ["Asra Alnazar", "The Arcana", ["asra", "asra alnazar"], ["devotion", "intuition", "gentleness"]],
  ["Julian Devorak", "The Arcana", ["julian", "ilya devorak", "julian devorak"], ["passion", "humor", "selflessness"]],
  ["Muriel", "The Arcana", ["muriel arcana", "muriel"], ["gentleness", "strength", "quiet loyalty"]],
  ["Nadia Satrinava", "The Arcana", ["nadia", "countess nadia", "nadia satrinava"], ["confidence", "wisdom", "grace"]],
  ["Portia Devorak", "The Arcana", ["portia", "pasha devorak", "portia devorak"], ["warmth", "courage", "resourcefulness"]],
  ["John MacTavish", "Call of Duty", ["soap", "soap mactavish", "john mactavish"], ["loyalty", "courage", "humor"]],
  ["Alejandro Vargas", "Call of Duty", ["alejandro", "colonel vargas", "alejandro vargas"], ["leadership", "passion", "loyalty"]],
  ["Logan Walker", "Call of Duty: Ghosts", ["logan", "logan walker"], ["courage", "focus", "loyalty"]],
  ["Phillip Graves", "Call of Duty", ["graves", "commander graves", "phillip graves"], ["confidence", "strategy", "presence"]],
  ["Halsin", "Baldur's Gate 3", ["halsin bg3", "first druid", "halsin"], ["steadiness", "wisdom", "warmth"]],
  ["Wyll Ravengard", "Baldur's Gate 3", ["wyll", "blade of frontiers", "wyll ravengard"], ["honor", "courage", "devotion"]],
  ["Karlach Cliffgate", "Baldur's Gate 3", ["karlach", "karlach cliffgate"], ["joy", "strength", "warmth"]],
  ["Lae'zel", "Baldur's Gate 3", ["laezel", "lae zel", "lae'zel"], ["resolve", "honesty", "strength"]],
  ["Minthara Baenre", "Baldur's Gate 3", ["minthara", "minthara baenre"], ["ambition", "confidence", "devotion"]],
  ["Sebastian", "Stardew Valley", ["sebastian stardew", "sebastian"], ["independence", "sensitivity", "quiet care"]],
  ["Elliott", "Stardew Valley", ["elliott stardew", "elliott"], ["romance", "eloquence", "gentleness"]],
  ["Shane", "Stardew Valley", ["shane stardew", "shane"], ["recovery", "honesty", "resilience"]],
  ["Harvey", "Stardew Valley", ["harvey stardew", "doctor harvey", "harvey"], ["care", "reliability", "gentleness"]],
  ["Cullen Rutherford", "Dragon Age", ["cullen", "commander cullen", "cullen rutherford"], ["recovery", "steadiness", "devotion"]],
  ["Dorian Pavus", "Dragon Age", ["dorian", "dorian pavus"], ["wit", "courage", "loyalty"]],
  ["Alistair Theirin", "Dragon Age", ["alistair", "alistair theirin"], ["humor", "loyalty", "gentleness"]],
  ["Kaidan Alenko", "Mass Effect", ["kaidan", "alenko", "kaidan alenko"], ["steadiness", "integrity", "care"]],
  ["Thane Krios", "Mass Effect", ["thane", "thane krios"], ["reflection", "devotion", "grace"]],
  ["Chris Redfield", "Resident Evil", ["chris", "redfield", "chris redfield"], ["protection", "strength", "loyalty"]],
  ["Carlos Oliveira", "Resident Evil", ["carlos", "carlos oliveira"], ["confidence", "courage", "warmth"]],
  ["Luis Serra", "Resident Evil", ["luis", "luis sera", "luis serra navarro", "luis serra"], ["charm", "redemption", "courage"]],
  ["Cloud Strife", "Final Fantasy VII", ["cloud", "cloud strife"], ["resilience", "protection", "quiet care"]],
  ["Sephiroth", "Final Fantasy VII", ["sephiroth ff7", "sephiroth"], ["presence", "focus", "power"]],
  ["Tifa Lockhart", "Final Fantasy VII", ["tifa", "tifa lockhart"], ["strength", "warmth", "loyalty"]],
  ["Aerith Gainsborough", "Final Fantasy VII", ["aerith", "aeris", "aerith gainsborough"], ["hope", "gentleness", "courage"]],
  ["Connor", "Detroit: Become Human", ["connor rk800", "rk800", "connor dbh", "connor"], ["curiosity", "growth", "focus"]],
  ["Hank Anderson", "Detroit: Become Human", ["hank", "lieutenant anderson", "hank anderson"], ["honesty", "protection", "recovery"]],
  ["Zagreus", "Hades", ["zagreus hades", "prince zagreus", "zagreus"], ["persistence", "warmth", "defiance"]],
  ["Thanatos", "Hades", ["thanatos hades", "thanatos"], ["devotion", "composure", "quiet care"]],
  ["Ellie Williams", "The Last of Us", ["ellie", "ellie williams"], ["resilience", "love", "courage"]],
  ["John Marston", "Red Dead Redemption", ["john", "john marston"], ["loyalty", "redemption", "endurance"]],
].map(([name, source, aliases, qualities]) => ({ name, source, aliases, qualities })) as CharacterProfile[];

const characterPatterns = [
  "{name} would remind you that {quality} can be quiet and still be real.",
  "You do not need to prove anything right now; {name} would stay until the pressure eased.",
  "Let {name}'s {quality} lend you a little steadiness for the next few minutes.",
  "{name} sees how hard you have been trying, including the parts no one else noticed.",
  "If today feels too sharp, imagine {name} making space beside you without asking for an explanation.",
  "{name} would tell you to take the next step at your own pace, not anyone else's.",
  "Your feelings are not an inconvenience to {name}; they are something worth listening to.",
  "Borrow a little of {name}'s {quality} and let the rest of the world wait.",
  "{name} would be proud of the way you kept going through something difficult.",
  "There is no performance required here—{name} is glad you arrived exactly as you are.",
  "{name} trusts that you can pause without giving up.",
  "You are allowed to be uncertain; {name} would still choose to stand with you.",
  "{name} would notice your {quality}, even on a day when you cannot see it yourself.",
  "The difficult moment is not the whole story, and {name} would help you remember that.",
  "Breathe slowly; {name} is not rushing you toward an answer.",
  "{name} would want you to speak to yourself with the same care you offer others.",
  "Even now, your capacity for {quality} has not disappeared; {name} can see it clearly.",
  "{name} would sit through the silence with you until words became easier.",
  "You have survived every version of this day so far; {name} thinks that matters.",
  "{name} would remind you that rest is part of the journey, not a failure to continue.",
  "Nothing about this moment makes you less worthy of gentleness in {name}'s eyes.",
  "{name} believes your boundaries deserve respect, including the ones you set with yourself.",
  "Take only what you need from today; {name} will help you leave the rest behind.",
  "Your {quality} is still here beneath the tiredness, and {name} has not forgotten it.",
  "{name} would rather hear the imperfect truth than watch you carry everything alone.",
  "You can begin again from this exact moment; {name} does not need you to erase what came before.",
  "{name} would make room for both your hope and your fear without asking either one to vanish.",
  "Let this be enough for now: you are here, you are breathing, and {name} is beside you.",
  "{name} would tell you that asking for comfort is a form of {quality}, not weakness.",
  "When you are ready, {name} will take the next small step with you.",
];

export const characters = profiles.map((profile) => ({
  ...profile,
  responses: characterPatterns.map((pattern, index) =>
    pattern
      .replaceAll("{name}", profile.name)
      .replaceAll("{quality}", profile.qualities[index % profile.qualities.length]),
  ),
}));

const openings = [
  "You are allowed to", "It is safe to", "For this moment, you can", "Today, you may",
  "Without explaining yourself, you can", "Even if the day feels unfinished, you can", "Gently, let yourself", "There is still time to",
  "You do not have to earn the right to", "No matter how today began, you can", "At your own pace, you may", "With no need to be perfect, you can",
  "When everything feels loud, you can", "As you take one slow breath, you can", "For as long as you need, you may", "In this small pocket of time, you can",
];
const actions = [
  "rest without calling it laziness", "begin again without judging the first attempt", "feel what you feel without apologizing",
  "choose the smaller next step", "leave one question unanswered", "ask for the care you need", "protect your energy without guilt",
  "be proud of quiet progress", "change your mind when new truth arrives", "take up space without becoming smaller",
  "trust the part of you that kept going", "let uncertainty exist beside hope", "step away from what is hurting you",
  "speak to yourself with patience", "make room for a softer plan", "remember that your needs matter",
  "set down what was never yours to carry", "move slowly and still move forward", "receive kindness without repayment",
  "accept that enough can be enough", "start with one honest breath", "keep a boundary that brings you peace",
  "notice the strength hidden in tenderness", "believe that this feeling will change", "return to what makes you feel like yourself",
  "let the next hour be uncomplicated", "choose care over urgency", "hold onto one small, true hope",
  "stop measuring your life by someone else's pace", "be unfinished and still be worthy", "listen to what your tiredness is saying",
  "take comfort seriously", "make a home inside your own attention", "let today be gentler than yesterday",
  "find one steady thing and stay near it", "remember that recovery is not linear", "give yourself credit for surviving",
  "release the need to solve everything tonight", "welcome calm without waiting for a reason", "belong here exactly as you are",
];
const endings = [
  "That choice is still progress.", "You have nothing to prove in this moment.", "A small act of care can change the shape of a day.",
  "Your pace is a valid pace.", "You deserve the kindness you keep offering everyone else.", "There is dignity in taking care of yourself.",
  "The next chapter does not require a perfect ending to this one.", "You are not behind; you are living through something real.",
  "This moment can be softer than the last.", "Your worth has not moved, even if your confidence has.",
];

export const generalResponses = openings.flatMap((opening, openingIndex) =>
  actions.map((action, actionIndex) => `${opening} ${action}. ${endings[(openingIndex + actionIndex) % endings.length]}`),
); // 16 × 40 = 640 complete responses

export const dataStats = {
  characterCount: characters.length,
  perCharacter: characterPatterns.length,
  characterResponses: characters.length * characterPatterns.length,
  generalResponses: generalResponses.length,
};
