export type CharacterProfile = {
  name: string;
  source: string;
  aliases: string[];
  qualities: [string, string, string];
};

const profiles: CharacterProfile[] = [
  ["Gojo Satoru", "Jujutsu Kaisen", ["gojo", "satoru", "satoru gojo"], ["confidence", "clarity", "strength"]],
  ["Geto Suguru", "Jujutsu Kaisen", ["geto", "suguru", "suguru geto"], ["composure", "conviction", "understanding"]],
  ["Nanami Kento", "Jujutsu Kaisen", ["nanami", "kento", "kento nanami"], ["steadiness", "practicality", "care"]],
  ["Megumi Fushiguro", "Jujutsu Kaisen", ["megumi", "fushiguro"], ["quiet courage", "loyalty", "discernment"]],
  ["Yuji Itadori", "Jujutsu Kaisen", ["yuji", "itadori", "yuuji"], ["kindness", "resolve", "warmth"]],
  ["Nobara Kugisaki", "Jujutsu Kaisen", ["nobara", "kugisaki"], ["self-respect", "boldness", "honesty"]],
  ["Levi Ackerman", "Attack on Titan", ["levi", "captain levi"], ["discipline", "protection", "precision"]],
  ["Eren Yeager", "Attack on Titan", ["eren", "eren jaeger", "yeager", "jaeger"], ["drive", "freedom", "determination"]],
  ["Mikasa Ackerman", "Attack on Titan", ["mikasa"], ["devotion", "strength", "steadiness"]],
  ["Armin Arlert", "Attack on Titan", ["armin"], ["insight", "hope", "gentleness"]],
  ["Osamu Dazai", "Bungo Stray Dogs", ["dazai", "osamu"], ["wit", "perception", "resilience"]],
  ["Chuuya Nakahara", "Bungo Stray Dogs", ["chuuya", "nakahara", "chūya"], ["fierceness", "loyalty", "grace"]],
  ["Atsushi Nakajima", "Bungo Stray Dogs", ["atsushi", "nakajima"], ["empathy", "growth", "bravery"]],
  ["Fyodor Dostoevsky", "Bungo Stray Dogs", ["fyodor", "dostoevsky"], ["patience", "intellect", "composure"]],
  ["Katsuki Bakugo", "My Hero Academia", ["bakugo", "bakugou", "katsuki", "kacchan"], ["ambition", "honesty", "tenacity"]],
  ["Izuku Midoriya", "My Hero Academia", ["deku", "izuku", "midoriya"], ["compassion", "courage", "effort"]],
  ["Shoto Todoroki", "My Hero Academia", ["shoto", "shouto", "todoroki"], ["calm", "growth", "integrity"]],
  ["Keigo Takami", "My Hero Academia", ["hawks", "keigo", "takami"], ["freedom", "perception", "ease"]],
  ["Shota Aizawa", "My Hero Academia", ["aizawa", "eraserhead", "eraser head", "shota"], ["reliability", "patience", "quiet care"]],
  ["Denki Kaminari", "My Hero Academia", ["denki", "kaminari"], ["brightness", "friendship", "spontaneity"]],
  ["L Lawliet", "Death Note", ["l", "lawliet", "ryuzaki", "ryuuzaki"], ["curiosity", "logic", "focus"]],
  ["Light Yagami", "Death Note", ["light", "yagami", "kira"], ["focus", "strategy", "confidence"]],
  ["Mello", "Death Note", ["mihael keehl", "mello"], ["fire", "ambition", "resourcefulness"]],
  ["Near", "Death Note", ["nate river", "near"], ["calm", "reason", "patience"]],
  ["Kakashi Hatake", "Naruto", ["kakashi", "hatake"], ["wisdom", "adaptability", "loyalty"]],
  ["Itachi Uchiha", "Naruto", ["itachi", "uchiha itachi"], ["sacrifice", "foresight", "calm"]],
  ["Naruto Uzumaki", "Naruto", ["naruto", "uzumaki"], ["hope", "persistence", "belonging"]],
  ["Sasuke Uchiha", "Naruto", ["sasuke", "uchiha sasuke"], ["resolve", "independence", "growth"]],
  ["Gaara", "Naruto", ["gaara of the sand", "gaara"], ["healing", "calm", "understanding"]],
  ["Hinata Hyuga", "Naruto", ["hinata", "hyuga", "hyuuga"], ["gentleness", "courage", "devotion"]],
  ["Killua Zoldyck", "Hunter x Hunter", ["killua", "zoldyck"], ["loyalty", "quickness", "tenderness"]],
  ["Gon Freecss", "Hunter x Hunter", ["gon", "freecss"], ["optimism", "curiosity", "heart"]],
  ["Kurapika", "Hunter x Hunter", ["kurapika"], ["focus", "loyalty", "dignity"]],
  ["Hisoka Morow", "Hunter x Hunter", ["hisoka", "morow"], ["confidence", "unpredictability", "focus"]],
  ["Chrollo Lucilfer", "Hunter x Hunter", ["chrollo", "lucilfer", "kuroro"], ["composure", "curiosity", "presence"]],
  ["Edward Elric", "Fullmetal Alchemist", ["edward", "ed elric", "fullmetal"], ["resolve", "ingenuity", "devotion"]],
  ["Roy Mustang", "Fullmetal Alchemist", ["roy", "mustang", "flame alchemist"], ["ambition", "leadership", "care"]],
  ["Rintaro Okabe", "Steins;Gate", ["okabe", "rintaro", "hououin kyouma"], ["imagination", "devotion", "persistence"]],
  ["Spike Spiegel", "Cowboy Bebop", ["spike", "spiegel"], ["ease", "adaptability", "depth"]],
  ["Vash the Stampede", "Trigun", ["vash", "stampede"], ["mercy", "hope", "endurance"]],
  ["Kyo Sohma", "Fruits Basket", ["kyo", "kyou", "sohma"], ["honesty", "growth", "warmth"]],
  ["Tohru Honda", "Fruits Basket", ["tohru", "tooru", "honda"], ["kindness", "acceptance", "hope"]],
  ["Howl Pendragon", "Howl's Moving Castle", ["howl", "pendragon", "howl jenkins"], ["wonder", "sensitivity", "courage"]],
  ["Sophie Hatter", "Howl's Moving Castle", ["sophie", "hatter"], ["steadiness", "wisdom", "care"]],
  ["Haku", "Spirited Away", ["kohaku", "nigihayami kohakunushi", "haku"], ["guidance", "calm", "loyalty"]],
  ["Loid Forger", "Spy x Family", ["loid", "twilight", "loid forger"], ["reliability", "resourcefulness", "care"]],
  ["Yor Forger", "Spy x Family", ["yor", "thorn princess"], ["devotion", "strength", "gentleness"]],
  ["Anya Forger", "Spy x Family", ["anya"], ["joy", "curiosity", "belonging"]],
  ["Kageyama Tobio", "Haikyu!!", ["kageyama", "tobio", "king of the court"], ["precision", "effort", "growth"]],
  ["Hinata Shoyo", "Haikyu!!", ["shoyo", "shouyou", "hinata shoyo"], ["energy", "hope", "persistence"]],
  ["Tetsuro Kuroo", "Haikyu!!", ["kuroo", "tetsuro", "tetsurou"], ["wit", "leadership", "perception"]],
  ["Kei Tsukishima", "Haikyu!!", ["tsukishima", "tsukki", "kei"], ["insight", "composure", "growth"]],
  ["Toru Oikawa", "Haikyu!!", ["oikawa", "tooru", "toru"], ["effort", "charisma", "resilience"]],
  ["Kenma Kozume", "Haikyu!!", ["kenma", "kozume"], ["thoughtfulness", "strategy", "quiet loyalty"]],
  ["Sakusa Kiyoomi", "Haikyu!!", ["sakusa", "kiyoomi", "omi"], ["precision", "boundaries", "consistency"]],
  ["Giyu Tomioka", "Demon Slayer", ["giyu", "giyuu", "tomioka"], ["calm", "protection", "integrity"]],
  ["Kyojuro Rengoku", "Demon Slayer", ["rengoku", "kyojuro", "kyoujurou"], ["warmth", "courage", "purpose"]],
  ["Tanjiro Kamado", "Demon Slayer", ["tanjiro", "tanjirou", "kamado"], ["compassion", "patience", "resolve"]],
  ["Nezuko Kamado", "Demon Slayer", ["nezuko"], ["gentleness", "protection", "resilience"]],
  ["Muichiro Tokito", "Demon Slayer", ["muichiro", "mui", "tokito"], ["clarity", "talent", "quietness"]],
  ["Mitsuri Kanroji", "Demon Slayer", ["mitsuri", "kanroji"], ["love", "strength", "openness"]],
  ["Shinobu Kocho", "Demon Slayer", ["shinobu", "kocho", "kochou"], ["grace", "intelligence", "resolve"]],
  ["Sebastian Michaelis", "Black Butler", ["sebastian", "michaelis"], ["competence", "composure", "attention"]],
  ["Ciel Phantomhive", "Black Butler", ["ciel", "phantomhive"], ["resolve", "intelligence", "dignity"]],
  ["Tamaki Suoh", "Ouran High School Host Club", ["tamaki", "suoh", "suou"], ["warmth", "theatricality", "generosity"]],
  ["Haruhi Fujioka", "Ouran High School Host Club", ["haruhi", "fujioka"], ["levelheadedness", "honesty", "kindness"]],
  ["Jinshi", "The Apothecary Diaries", ["jinshi"], ["grace", "persistence", "perception"]],
  ["Maomao", "The Apothecary Diaries", ["mao mao", "maomao"], ["curiosity", "candor", "intelligence"]],
  ["Frieren", "Frieren: Beyond Journey's End", ["frieren"], ["patience", "memory", "quiet care"]],
  ["Fern", "Frieren: Beyond Journey's End", ["fern"], ["steadiness", "discipline", "devotion"]],
  ["Lelouch Lamperouge", "Code Geass", ["lelouch", "zero", "lamperouge"], ["strategy", "resolve", "devotion"]],
  ["Suzaku Kururugi", "Code Geass", ["suzaku", "kururugi"], ["idealism", "discipline", "courage"]],
  ["Rei Ayanami", "Neon Genesis Evangelion", ["rei", "ayanami"], ["stillness", "reflection", "gentleness"]],
  ["Kaworu Nagisa", "Neon Genesis Evangelion", ["kaworu", "nagisa"], ["acceptance", "calm", "understanding"]],
  ["Shinji Ikari", "Neon Genesis Evangelion", ["shinji", "ikari"], ["sensitivity", "effort", "growth"]],
  ["Asuka Langley", "Neon Genesis Evangelion", ["asuka", "langley", "soryu", "shikinami"], ["fire", "independence", "determination"]],
  ["Dimitri Alexandre Blaiddyd", "Fire Emblem", ["dimitri", "blaiddyd"], ["honor", "tenderness", "recovery"]],
  ["Claude von Riegan", "Fire Emblem", ["claude", "riegan"], ["curiosity", "wit", "vision"]],
  ["Astarion", "Baldur's Gate 3", ["astarion ancunin", "astarion"], ["wit", "survival", "self-discovery"]],
  ["Gale Dekarios", "Baldur's Gate 3", ["gale", "dekarios"], ["curiosity", "eloquence", "devotion"]],
  ["Shadowheart", "Baldur's Gate 3", ["shart", "jenevelle", "shadowheart"], ["resilience", "faith", "gentleness"]],
  ["Zhongli", "Genshin Impact", ["rex lapis", "morax", "zhongli"], ["wisdom", "steadiness", "perspective"]],
  ["Kaedehara Kazuha", "Genshin Impact", ["kazuha", "kaedehara"], ["freedom", "poise", "reflection"]],
  ["Xiao", "Genshin Impact", ["alatus", "xiao"], ["protection", "endurance", "quiet care"]],
  ["Alhaitham", "Genshin Impact", ["al haitham", "alhaitham"], ["clarity", "independence", "reason"]],
  ["Dan Heng", "Honkai: Star Rail", ["danheng", "dan heng", "imbibitor lunae"], ["calm", "loyalty", "reflection"]],
  ["Jing Yuan", "Honkai: Star Rail", ["jingyuan", "jing yuan", "the general"], ["patience", "strategy", "warmth"]],
  ["Link", "The Legend of Zelda", ["hero of hyrule", "link"], ["courage", "resourcefulness", "quiet devotion"]],
  ["Harry Potter", "Harry Potter", ["harry", "the boy who lived", "potter"], ["courage", "loyalty", "hope"]],
  ["Hermione Granger", "Harry Potter", ["hermione", "granger"], ["intelligence", "loyalty", "conviction"]],
  ["Draco Malfoy", "Harry Potter", ["draco", "malfoy"], ["complexity", "ambition", "growth"]],
  ["Severus Snape", "Harry Potter", ["snape", "severus", "professor snape"], ["devotion", "resolve", "restraint"]],
  ["Sirius Black", "Harry Potter", ["sirius", "padfoot"], ["loyalty", "freedom", "warmth"]],
  ["Remus Lupin", "Harry Potter", ["remus", "lupin", "moony"], ["gentleness", "wisdom", "resilience"]],
  ["Newt Scamander", "Fantastic Beasts", ["newt", "scamander"], ["kindness", "curiosity", "quiet courage"]],
  ["Loki Laufeyson", "Marvel", ["loki", "laufeyson", "god of mischief"], ["wit", "adaptability", "self-discovery"]],
  ["Peter Parker", "Marvel", ["peter", "spider man", "spiderman"], ["responsibility", "kindness", "resilience"]],
  ["Tony Stark", "Marvel", ["tony", "stark", "iron man", "ironman"], ["ingenuity", "confidence", "care"]],
  ["Bucky Barnes", "Marvel", ["bucky", "winter soldier", "james barnes"], ["recovery", "loyalty", "endurance"]],
  ["Steve Rogers", "Marvel", ["steve", "captain america", "cap"], ["integrity", "courage", "steadiness"]],
  ["Wanda Maximoff", "Marvel", ["wanda", "scarlet witch"], ["resilience", "love", "power"]],
  ["Natasha Romanoff", "Marvel", ["natasha", "romanoff", "black widow"], ["resourcefulness", "loyalty", "strength"]],
  ["Thor Odinson", "Marvel", ["thor", "odinson", "god of thunder"], ["courage", "warmth", "renewal"]],
  ["Bruce Wayne", "DC Comics", ["bruce", "wayne", "batman"], ["resolve", "protection", "discipline"]],
  ["Dick Grayson", "DC Comics", ["dick", "grayson", "nightwing", "robin"], ["hope", "leadership", "warmth"]],
  ["Jason Todd", "DC Comics", ["jason", "todd", "red hood"], ["survival", "fierceness", "loyalty"]],
  ["Clark Kent", "DC Comics", ["clark", "kent", "superman", "kal el"], ["hope", "gentleness", "strength"]],
  ["Diana Prince", "DC Comics", ["diana", "wonder woman"], ["truth", "compassion", "courage"]],
  ["Zuko", "Avatar: The Last Airbender", ["prince zuko", "fire lord zuko", "zuko"], ["growth", "honor", "perseverance"]],
  ["Katara", "Avatar: The Last Airbender", ["katara"], ["compassion", "determination", "healing"]],
  ["Azula", "Avatar: The Last Airbender", ["princess azula", "azula"], ["precision", "ambition", "intensity"]],
  ["Aang", "Avatar: The Last Airbender", ["avatar aang", "aang"], ["hope", "balance", "kindness"]],
  ["Sokka", "Avatar: The Last Airbender", ["sokka"], ["wit", "resourcefulness", "loyalty"]],
  ["Percy Jackson", "Percy Jackson", ["percy", "seaweed brain"], ["loyalty", "humor", "courage"]],
  ["Annabeth Chase", "Percy Jackson", ["annabeth", "wise girl"], ["wisdom", "strategy", "devotion"]],
  ["Nico di Angelo", "Percy Jackson", ["nico", "di angelo", "ghost king"], ["resilience", "independence", "loyalty"]],
  ["Will Solace", "Percy Jackson", ["will", "solace"], ["warmth", "healing", "optimism"]],
  ["Wednesday Addams", "The Addams Family", ["wednesday", "wednesday addams"], ["independence", "candor", "composure"]],
  ["Kaz Brekker", "Six of Crows", ["kaz", "brekker", "dirtyhands"], ["strategy", "survival", "resolve"]],
  ["Inej Ghafa", "Six of Crows", ["inej", "ghafa", "the wraith"], ["faith", "courage", "grace"]],
  ["Cardan Greenbriar", "The Folk of the Air", ["cardan", "high king cardan"], ["wit", "vulnerability", "growth"]],
  ["Jude Duarte", "The Folk of the Air", ["jude", "jude duarte"], ["ambition", "courage", "resourcefulness"]],
  ["Peeta Mellark", "The Hunger Games", ["peeta", "mellark"], ["gentleness", "hope", "steadiness"]],
  ["Katniss Everdeen", "The Hunger Games", ["katniss", "everdeen", "mockingjay"], ["protection", "resolve", "love"]],
  ["Frodo Baggins", "The Lord of the Rings", ["frodo", "baggins"], ["endurance", "mercy", "quiet courage"]],
  ["Legolas", "The Lord of the Rings", ["legolas greenleaf", "legolas"], ["grace", "loyalty", "perception"]],
  ["Aragorn", "The Lord of the Rings", ["strider", "elessar", "aragorn"], ["leadership", "humility", "steadiness"]],
  ["Samwise Gamgee", "The Lord of the Rings", ["sam", "samwise", "sam gamgee"], ["loyalty", "hope", "devotion"]],
].map(([name, source, aliases, qualities]) => ({ name, source, aliases, qualities })) as CharacterProfile[];

const characterPatterns = [
  "{name} would remind you that {quality} can be quiet and still be real.",
  "You do not need to prove anything right now; {name} would stay until the pressure eased.",
  "Let {name}'s {quality} lend you a little steadiness for the next few minutes.",
  "{name} sees how hard you have been trying, including the parts no one else noticed.",
  "If today feels too sharp, imagine {name} making space beside you without asking for an explanation.",
  "{name} would tell you to take the next step at your own pace, not anyone else's.",
  "Your feelings are not an inconvenience to {name}; they are something worth listening to.",
  "Borrow a little of {name}'s {quality} and let the rest of the world wait.",
  "{name} would be proud of the way you kept going through something difficult.",
  "There is no performance required here—{name} is glad you arrived exactly as you are.",
  "{name} trusts that you can pause without giving up.",
  "You are allowed to be uncertain; {name} would still choose to stand with you.",
  "{name} would notice your {quality}, even on a day when you cannot see it yourself.",
  "The difficult moment is not the whole story, and {name} would help you remember that.",
  "Breathe slowly; {name} is not rushing you toward an answer.",
  "{name} would want you to speak to yourself with the same care you offer others.",
  "Even now, your capacity for {quality} has not disappeared; {name} can see it clearly.",
  "{name} would sit through the silence with you until words became easier.",
  "You have survived every version of this day so far; {name} thinks that matters.",
  "{name} would remind you that rest is part of the journey, not a failure to continue.",
  "Nothing about this moment makes you less worthy of gentleness in {name}'s eyes.",
  "{name} believes your boundaries deserve respect, including the ones you set with yourself.",
  "Take only what you need from today; {name} will help you leave the rest behind.",
  "Your {quality} is still here beneath the tiredness, and {name} has not forgotten it.",
  "{name} would rather hear the imperfect truth than watch you carry everything alone.",
  "You can begin again from this exact moment; {name} does not need you to erase what came before.",
  "{name} would make room for both your hope and your fear without asking either one to vanish.",
  "Let this be enough for now: you are here, you are breathing, and {name} is beside you.",
  "{name} would tell you that asking for comfort is a form of {quality}, not weakness.",
  "When you are ready, {name} will take the next small step with you.",
];

export const characters = profiles.map((profile) => ({
  ...profile,
  responses: characterPatterns.map((pattern, index) =>
    pattern
      .replaceAll("{name}", profile.name)
      .replaceAll("{quality}", profile.qualities[index % profile.qualities.length]),
  ),
}));

const openings = [
  "You are allowed to", "It is safe to", "For this moment, you can", "Today, you may",
  "Without explaining yourself, you can", "Even if the day feels unfinished, you can", "Gently, let yourself", "There is still time to",
  "You do not have to earn the right to", "No matter how today began, you can", "At your own pace, you may", "With no need to be perfect, you can",
  "When everything feels loud, you can", "As you take one slow breath, you can", "For as long as you need, you may", "In this small pocket of time, you can",
];
const actions = [
  "rest without calling it laziness", "begin again without judging the first attempt", "feel what you feel without apologizing",
  "choose the smaller next step", "leave one question unanswered", "ask for the care you need", "protect your energy without guilt",
  "be proud of quiet progress", "change your mind when new truth arrives", "take up space without becoming smaller",
  "trust the part of you that kept going", "let uncertainty exist beside hope", "step away from what is hurting you",
  "speak to yourself with patience", "make room for a softer plan", "remember that your needs matter",
  "set down what was never yours to carry", "move slowly and still move forward", "receive kindness without repayment",
  "accept that enough can be enough", "start with one honest breath", "keep a boundary that brings you peace",
  "notice the strength hidden in tenderness", "believe that this feeling will change", "return to what makes you feel like yourself",
  "let the next hour be uncomplicated", "choose care over urgency", "hold onto one small, true hope",
  "stop measuring your life by someone else's pace", "be unfinished and still be worthy", "listen to what your tiredness is saying",
  "take comfort seriously", "make a home inside your own attention", "let today be gentler than yesterday",
  "find one steady thing and stay near it", "remember that recovery is not linear", "give yourself credit for surviving",
  "release the need to solve everything tonight", "welcome calm without waiting for a reason", "belong here exactly as you are",
];
const endings = [
  "That choice is still progress.", "You have nothing to prove in this moment.", "A small act of care can change the shape of a day.",
  "Your pace is a valid pace.", "You deserve the kindness you keep offering everyone else.", "There is dignity in taking care of yourself.",
  "The next chapter does not require a perfect ending to this one.", "You are not behind; you are living through something real.",
  "This moment can be softer than the last.", "Your worth has not moved, even if your confidence has.",
];

export const generalResponses = openings.flatMap((opening, openingIndex) =>
  actions.map((action, actionIndex) => `${opening} ${action}. ${endings[(openingIndex + actionIndex) % endings.length]}`),
); // 16 × 40 = 640 complete responses

export const dataStats = {
  characterCount: characters.length,
  perCharacter: characterPatterns.length,
  characterResponses: characters.length * characterPatterns.length,
  generalResponses: generalResponses.length,
};
